=== DavidZamanian/Bachelor-thesis-blockchain-for-medical-records/server/jsonHandling/examples/EHR_entry_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "date": {
        "type": "string"
    },
    "patientID": {
      "type": "string"
    },
    "healthcareInstitution": {
      "type": "string"
    },
    "medicalPersonnel": {
      "type": "string"
    },
    "details": {
      "type": "string"
    },
    "diagnoses": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "prescriptions": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "date",
    "patientID",
    "healthcareInstitution",
    "medicalPersonnel",
    "details"
  ],
  "additionalProperties": false
}

=== DavidZamanian/Bachelor-thesis-blockchain-for-medical-records/test/json_examples/EHR_entry.json
{
    "date": "2022-02-25",
    "patientID": "fdjsajkfvhkcjasjcas",
    "healthcareInstitution": "Ostra sjukhuset",
    "medicalPersonnel": "Lolly Pop",
    "details": "thick throat",
    "diagnoses": ["allergy against birch"],
    "prescriptions": [
        "pollenStopperPill, 2 mg 3 times / day, 4 hrs in between", 
        "pollenStopperSpray 2 pills 2 times / day"
    ]
}
